
name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies and Workloads
      run: |
        dotnet restore Castorix.sln
        dotnet workload restore

    - name: Build Solution
      run: dotnet build Castorix.sln --configuration Release --framework net9.0-windows

    - name: Run Tests (if applicable)
      run: dotnet test Castorix.sln
